#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tonghua?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 5120154230
#    #   druid增加的配置
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    maxActive: 20
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    #   testWhileIdle在不影响性能情况下保证安全性
#    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#
#mybatis:
#  configuration:
#    aggressive-lazy-loading: false
#    lazy-loading-enabled: true
#    map-underscore-to-camel-case: true
#spring.datasource.initialization-mode=always
#spring.datasource.schema=- classpath:/sql/user_blog.sql